table octopus_spla_export_new
	lineageTag: 7b1bf836-588b-44a1-8748-92da64d468d6

	measure Mesure = 1
		formatString: 0
		lineageTag: 7f9924cc-e3a2-49a7-8b9e-198d57cc1b1a

	column context
		dataType: string
		lineageTag: a2599793-3364-4dad-ac3f-db967b2c48b6
		summarizeBy: none
		sourceColumn: context

		annotation SummarizationSetBy = Automatic

	column customer_internal_id
		dataType: string
		lineageTag: be0cb2ab-f041-4d6b-865c-efac1b87449a
		summarizeBy: none
		sourceColumn: customer_internal_id

		annotation SummarizationSetBy = Automatic

	column object_ou
		dataType: string
		lineageTag: 46f14cc5-abb9-4683-af68-0cc5a633b1dc
		summarizeBy: none
		sourceColumn: object_ou

		annotation SummarizationSetBy = Automatic

	column object_extra_fields
		dataType: string
		lineageTag: 83972fc3-69d9-49ef-a0d2-cea60be5d734
		summarizeBy: none
		sourceColumn: object_extra_fields

		annotation SummarizationSetBy = Automatic

	column object_office_location
		dataType: string
		lineageTag: aec22248-70bc-45fb-b3b2-1b1ff075b22f
		summarizeBy: none
		sourceColumn: object_office_location

		annotation SummarizationSetBy = Automatic

	column installed_software_name
		dataType: string
		lineageTag: 35dcee7f-1622-40f9-890d-122c299723ea
		summarizeBy: none
		sourceColumn: installed_software_name

		annotation SummarizationSetBy = Automatic

	column installed_software_access_devices
		dataType: string
		lineageTag: 9a673588-b544-4ab0-b85c-31b1aa799248
		summarizeBy: none
		sourceColumn: installed_software_access_devices

		annotation SummarizationSetBy = Automatic

	column installed_software_remote_access_groups
		dataType: string
		lineageTag: f0f283ba-fd61-45ae-a86b-0c6f2f54cb3f
		summarizeBy: none
		sourceColumn: installed_software_remote_access_groups

		annotation SummarizationSetBy = Automatic

	column installed_software_deleted
		dataType: string
		lineageTag: 0637bbc2-649c-4278-8450-442b9c3819ba
		summarizeBy: none
		sourceColumn: installed_software_deleted

		annotation SummarizationSetBy = Automatic

	column license_part_number
		dataType: string
		lineageTag: e0472c39-351b-4c42-9c26-1e5ab2dd1f01
		summarizeBy: none
		sourceColumn: license_part_number

		annotation SummarizationSetBy = Automatic

	column license_vendor_part_number
		dataType: string
		lineageTag: dd78b601-000d-49dd-9dfa-f6595907fa60
		summarizeBy: none
		sourceColumn: license_vendor_part_number

		annotation SummarizationSetBy = Automatic

	column license_own_part_number
		dataType: string
		lineageTag: ed4323aa-5538-4b06-b27a-ae347271b314
		summarizeBy: none
		sourceColumn: license_own_part_number

		annotation SummarizationSetBy = Automatic

	column license_readable_name
		dataType: string
		lineageTag: 2e34bf06-0a02-4368-91a5-1b75b622d0d7
		summarizeBy: none
		sourceColumn: license_readable_name

		annotation SummarizationSetBy = Automatic

	column license_name
		dataType: string
		lineageTag: 5d824a02-426e-4ef6-b284-48cd9d76060c
		summarizeBy: none
		sourceColumn: license_name

		annotation SummarizationSetBy = Automatic

	column license_count
		dataType: int64
		formatString: 0
		lineageTag: 42a972af-78c7-4333-89e9-fd3b61c3d385
		summarizeBy: sum
		sourceColumn: license_count

		annotation SummarizationSetBy = Automatic

	column observation_period
		dataType: string
		lineageTag: 82cfc594-2fc1-4ba3-89ea-07daaa5ad9dd
		summarizeBy: none
		sourceColumn: observation_period

		annotation SummarizationSetBy = Automatic

	partition octopus_spla_export_new = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\smouffok\Downloads\VSRepo\VSTest\octopus_spla_export_new.csv"),[Delimiter=";", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"context", type text}, {"customer_internal_id", type text}, {"object_ou", type text}, {"object_extra_fields", type text}, {"object_office_location", type text}, {"installed_software_name", type text}, {"installed_software_access_devices", type text}, {"installed_software_remote_access_groups", type text}, {"installed_software_deleted", type text}, {"license_part_number", type text}, {"license_vendor_part_number", type text}, {"license_own_part_number", type text}, {"license_readable_name", type text}, {"license_name", type text}, {"license_count", Int64.Type}, {"observation_period", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

